# Generated by Django 2.1.5 on 2019-05-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('description', models.CharField(max_length=255, verbose_name='descrição')),
                ('departament', models.CharField(max_length=255, verbose_name='departamento')),
                ('category', models.CharField(max_length=20, verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-created'],
            },
        ),
    ]
