# Generated by Django 2.1.5 on 2019-05-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190502_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.PositiveIntegerField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=1, verbose_name='preço'),
            preserve_default=False,
        ),
    ]
